In [50]:
import pandas as pd
train = pd.read_csv(r'I:\PYTHON\AI_datamining\data\raw\train.csv')
train.head(20)

,Attrition,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,37,Travel_Rarely,Research & Development,1,4,Life Sciences,77,1,Male,...,3,80,1,7,2,4,7,5,0,7
1,0,54,Travel_Frequently,Research & Development,1,4,Life Sciences,1245,4,Female,...,1,80,1,33,2,1,5,4,1,4
2,1,34,Travel_Frequently,Research & Development,7,3,Life Sciences,147,1,Male,...,4,80,0,9,3,3,9,7,0,6
3,0,39,Travel_Rarely,Research & Development,1,1,Life Sciences,1026,4,Female,...,3,80,1,21,3,3,21,6,11,8
4,1,28,Travel_Frequently,Research & Development,1,3,Medical,1111,1,Male,...,1,80,2,1,2,3,1,0,0,0
5,0,24,Travel_Rarely,Sales,4,1,Medical,1445,4,Female,...,3,80,2,5,3,3,5,4,0,3
6,0,29,Travel_Rarely,Research & Development,9,5,Other,455,2,Male,...,3,80,0,4,2,3,3,2,2,2
7,0,36,Travel_Rarely,Sales,2,2,Medical,513,2,Male,...,2,80,2,10,2,3,10,9,9,0
8,0,33,Travel_Rarely,Research & Development,4,4,Medical,305,3,Female,...,4,80,0,7,3,3,3,2,1,1
9,0,34,Travel_Rarely,Research & Development,2,4,Technical Degree,1383,3,Female,...,4,80,0,14,2,4,14,11,4,11
10,1,24,Travel_Rarely,Human Resources,22,1,Human Resources,1714,4,Male,...,3,80,1,1,2,3,1,0,0,0
11,0,35,Travel_Rarely,Research & Development,10,4,Medical,1587,1,Female,...,3,80,0,10,4,3,5,2,0,4
12,1,30,Travel_Rarely,Research & Development,3,3,Technical Degree,297,4,Female,...,3,80,0,8,5,3,5,2,0,4
13,0,54,Travel_Rarely,Research & Development,8,4,Life Sciences,578,3,Female,...,3,80,0,19,3,3,1,0,0,0
14,0,34,Travel_Rarely,Research & Development,1,3,Life Sciences,1447,4,Female,...,1,80,1,7,2,2,5,4,0,2
15,0,47,Travel_Rarely,Sales,2,4,Life Sciences,925,4,Female,...,1,80,0,3,3,2,3,2,1,2
16,0,36,Non-Travel,Sales,15,4,Marketing,2036,4,Male,...,1,80,1,15,4,2,15,12,11,11
17,0,35,Travel_Rarely,Research & Development,1,4,Medical,1172,4,Male,...,2,80,1,10,2,3,8,0,1,7
18,0,29,Travel_Rarely,Sales,19,3,Life Sciences,1497,3,Male,...,3,80,2,10,3,3,10,7,0,4
19,1,56,Travel_Rarely,Research & Development,14,4,Life Sciences,161,2,Female,...,1,80,3,7,2,3,5,4,4,3

In [51]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition                 1100 non-null   int64
 1   Age                       1100 non-null   int64
 2   BusinessTravel            1100 non-null   object
 3   Department                1100 non-null   object
 4   DistanceFromHome          1100 non-null   int64
 5   Education                 1100 non-null   int64
 6   EducationField            1100 non-null   object
 7   EmployeeNumber            1100 non-null   int64
 8   EnvironmentSatisfaction   1100 non-null   int64
 9   Gender                    1100 non-null   object
 10  JobInvolvement            1100 non-null   int64
 11  JobLevel                  1100 non-null   int64
 12  JobRole                   1100 non-null   object
 13  JobSatisfaction           1100 non-null   int64
 14  MaritalStatus             1100 non-null   object
 15  MonthlyIncome             1100 non-null   int64
 16  NumCompaniesWorked        1100 non-null   int64
 17  Over18                    1100 non-null   object
 18  OverTime                  1100 non-null   object
 19  PercentSalaryHike         1100 non-null   int64
 20  PerformanceRating         1100 non-null   int64
 21  RelationshipSatisfaction  1100 non-null   int64
 22  StandardHours             1100 non-null   int64
 23  StockOptionLevel          1100 non-null   int64
 24  TotalWorkingYears         1100 non-null   int64
 25  TrainingTimesLastYear     1100 non-null   int64
 26  WorkLifeBalance           1100 non-null   int64
 27  YearsAtCompany            1100 non-null   int64
 28  YearsInCurrentRole        1100 non-null   int64
 29  YearsSinceLastPromotion   1100 non-null   int64
 30  YearsWithCurrManager      1100 non-null   int64
dtypes: int64(23), object(8)
memory usage: 266.5+ KB

In [52]:
import toad
toad.detect(train)

,type,size,missing,unique,mean_or_top1,std_or_top2,min_or_top3,1%_or_top4,10%_or_top5,50%_or_bottom5,75%_or_bottom4,90%_or_bottom3,99%_or_bottom2,max_or_bottom1
Attrition,int64,1100,0.00%,2,0.161818,0.368451,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
Age,int64,1100,0.00%,43,36.999091,9.03723,18.0,20.0,26.0,36.0,43.0,50.0,59.0,60.0
BusinessTravel,object,1100,0.00%,3,Travel_Rarely:71.55%,Travel_Frequently:18.64%,Non-Travel:9.82%,None,None,None,None,Travel_Rarely:71.55%,Travel_Frequently:18.64%,Non-Travel:9.82%
Department,object,1100,0.00%,3,Research & Development:66.09%,Sales:30.09%,Human Resources:3.82%,None,None,None,None,Research & Development:66.09%,Sales:30.09%,Human Resources:3.82%
DistanceFromHome,int64,1100,0.00%,29,9.427273,8.196694,1.0,1.0,1.0,7.0,15.0,24.0,29.0,29.0
Education,int64,1100,0.00%,5,2.922727,1.022242,1.0,1.0,1.0,3.0,4.0,4.0,5.0,5.0
EducationField,object,1100,0.00%,6,Life Sciences:42.00%,Medical:30.64%,Marketing:11.55%,Technical Degree:8.36%,Other:5.73%,Medical:30.64%,Marketing:11.55%,Technical Degree:8.36%,Other:5.73%,Human Resources:1.73%
EmployeeNumber,int64,1100,0.00%,1100,1028.157273,598.915204,1.0,21.98,210.5,1026.5,1556.5,1853.1,2049.02,2065.0
EnvironmentSatisfaction,int64,1100,0.00%,4,2.725455,1.098053,1.0,1.0,1.0,3.0,4.0,4.0,4.0,4.0
Gender,object,1100,0.00%,2,Male:59.36%,Female:40.64%,None,None,None,None,None,None,Male:59.36%,Female:40.64%
JobInvolvement,int64,1100,0.00%,4,2.730909,0.706366,1.0,1.0,2.0,3.0,3.0,3.0,4.0,4.0
JobLevel,int64,1100,0.00%,5,2.054545,1.107805,1.0,1.0,1.0,2.0,3.0,4.0,5.0,5.0
JobRole,object,1100,0.00%,9,Sales Executive:22.45%,Research Scientist:20.09%,Laboratory Technician:18.64%,Manufacturing Director:9.18%,Healthcare Representative:9.09%,Healthcare Representative:9.09%,Manager:7.27%,Sales Representative:5.18%,Research Director:5.09%,Human Resources:3.00%
JobSatisfaction,int64,1100,0.00%,4,2.732727,1.109731,1.0,1.0,1.0,3.0,4.0,4.0,4.0,4.0
MaritalStatus,object,1100,0.00%,3,Married:45.45%,Single:32.91%,Divorced:21.64%,None,None,None,None,Married:45.45%,Single:32.91%,Divorced:21.64%
MonthlyIncome,int64,1100,0.00%,1028,6483.620909,4715.293419,1009.0,1280.93,2312.8,4857.0,8354.5,13881.2,19626.01,19999.0
NumCompaniesWorked,int64,1100,0.00%,10,2.683636,2.510017,0.0,0.0,0.0,2.0,4.0,7.0,9.0,9.0
Over18,object,1100,0.00%,1,Y:100.00%,None,None,None,None,None,None,None,None,Y:100.00%
OverTime,object,1100,0.00%,2,No:72.18%,Yes:27.82%,None,None,None,None,None,None,No:72.18%,Yes:27.82%
PercentSalaryHike,int64,1100,0.00%,15,15.235455,3.628571,11.0,11.0,11.0,14.0,18.0,21.0,25.0,25.0
PerformanceRating,int64,1100,0.00%,2,3.152727,0.359888,3.0,3.0,3.0,3.0,3.0,4.0,4.0,4.0
RelationshipSatisfaction,int64,1100,0.00%,4,2.696364,1.095356,1.0,1.0,1.0,3.0,4.0,4.0,4.0,4.0
StandardHours,int64,1100,0.00%,1,80.0,0.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0
StockOptionLevel,int64,1100,0.00%,4,0.788182,0.843347,0.0,0.0,0.0,1.0,1.0,2.0,3.0,3.0
TotalWorkingYears,int64,1100,0.00%,40,11.221818,7.825548,0.0,1.0,3.0,10.0,15.0,23.0,35.01,40.0
TrainingTimesLastYear,int64,1100,0.00%,7,2.807273,1.291514,0.0,0.0,2.0,3.0,3.0,5.0,6.0,6.0
WorkLifeBalance,int64,1100,0.00%,4,2.746364,0.701121,1.0,1.0,2.0,3.0,3.0,3.0,4.0,4.0
YearsAtCompany,int64,1100,0.00%,35,7.011818,6.223093,0.0,0.0,1.0,5.0,9.0,15.0,32.0,37.0
YearsInCurrentRole,int64,1100,0.00%,19,4.207273,3.618115,0.0,0.0,0.0,3.0,7.0,9.0,15.0,18.0
YearsSinceLastPromotion,int64,1100,0.00%,16,2.226364,3.31383,0.0,0.0,0.0,1.0,3.0,7.0,14.01,15.0
YearsWithCurrManager,int64,1100,0.00%,18,4.123636,3.597996,0.0,0.0,0.0,3.0,7.0,9.0,15.0,17.0

In [53]:
#去除无用特征
test = pd.read_csv(r'I:\PYTHON\AI_datamining\data\raw\test2.csv')
x_train = train.iloc[:,1:]
y_train = train.iloc[:,0]
x_test = test.iloc[:,:-1]
y_test = test.iloc[:,-1]

In [54]:
woe = toad.transform.WOETransformer()
x_train_woe = woe.fit_transform(x_train,y_train)

x_test_woe = woe.transform(x_test)

In [55]:
y_train.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1100 entries, 0 to 1099
Series name: Attrition
Non-Null Count  Dtype
--------------  -----
1100 non-null   int64
dtypes: int64(1)
memory usage: 8.7 KB

In [56]:
toad.detect(x_train_woe)

,type,size,missing,unique,mean_or_top1,std_or_top2,min_or_top3,1%_or_top4,10%_or_top5,50%_or_bottom5,75%_or_bottom4,90%_or_bottom3,99%_or_bottom2,max_or_bottom1
Age,float64,1100,0.00%,39,-0.164154,7.974012e-01,-1.533292,-1.533292,-1.245610,-0.237970,0.546149,0.728471,2.155587,2.561052
BusinessTravel,float64,1100,0.00%,3,-0.028134,2.944354e-01,-0.753134,-0.753134,-0.041336,-0.041336,-0.041336,0.404499,0.404499,0.404499
Department,float64,1100,0.00%,3,-0.015553,2.133625e-01,-0.168017,-0.168017,-0.168017,-0.168017,0.273505,0.273505,0.345479,0.345479
DistanceFromHome,float64,1100,0.00%,28,-0.062683,4.317732e-01,-0.994296,-0.994296,-0.398312,-0.132399,0.140684,0.440789,1.357080,1.357080
Education,float64,1100,0.00%,5,-0.019321,2.520835e-01,-1.188452,-1.188452,-0.124525,0.038105,0.038105,0.345479,0.345479,0.345479
EducationField,float64,1100,0.00%,6,-0.024368,2.665799e-01,-0.434680,-0.434680,-0.199920,-0.078005,-0.078005,0.487309,0.871572,0.871572
EmployeeNumber,float64,1100,0.00%,1,1.644762,3.909763e-14,1.644762,1.644762,1.644762,1.644762,1.644762,1.644762,1.644762,1.644762
EnvironmentSatisfaction,float64,1100,0.00%,4,-0.027420,2.815426e-01,-0.225330,-0.225330,-0.225330,-0.178414,-0.034880,0.527457,0.527457,0.527457
Gender,float64,1100,0.00%,2,-0.000707,4.578965e-02,-0.056026,-0.056026,-0.056026,0.037160,0.037160,0.037160,0.037160,0.037160
JobInvolvement,float64,1100,0.00%,4,-0.035899,3.253931e-01,-0.479132,-0.479132,-0.115582,-0.115582,0.048453,0.048453,1.159254,1.159254
JobLevel,float64,1100,0.00%,5,-0.131724,6.438397e-01,-1.613335,-1.613335,-0.574442,-0.279487,0.597279,0.597279,0.597279,0.597279
JobRole,float64,1100,0.00%,9,-0.162970,7.268851e-01,-1.651075,-1.651075,-1.299677,0.059421,0.318365,0.318365,1.253895,1.253895
JobSatisfaction,float64,1100,0.00%,4,-0.039893,3.441172e-01,-0.460655,-0.460655,-0.460655,-0.036541,0.092482,0.503066,0.503066,0.503066
MaritalStatus,float64,1100,0.00%,3,-0.082925,4.928615e-01,-0.639474,-0.639474,-0.639474,-0.310323,0.597069,0.597069,0.597069,0.597069
MonthlyIncome,float64,1100,0.00%,4,1.587728,2.118136e-01,0.546149,0.951614,1.644762,1.644762,1.644762,1.644762,1.644762,2.337909
NumCompaniesWorked,float64,1100,0.00%,10,-0.049085,3.873340e-01,-0.811974,-0.811974,-0.811974,0.189474,0.226102,0.329085,0.516296,0.516296
Over18,float64,1100,0.00%,1,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
OverTime,float64,1100,0.00%,2,-0.144546,6.438973e-01,-0.544095,-0.544095,-0.544095,-0.544095,0.892191,0.892191,0.892191,0.892191
PercentSalaryHike,float64,1100,0.00%,15,-0.054513,4.138411e-01,-0.920188,-0.920188,-0.891817,0.035324,0.127439,0.292369,1.308289,1.308289
PerformanceRating,float64,1100,0.00%,2,-0.004797,1.181172e-01,-0.054923,-0.054923,-0.054923,-0.054923,-0.054923,0.273282,0.273282,0.273282
RelationshipSatisfaction,float64,1100,0.00%,4,-0.008307,1.557881e-01,-0.150614,-0.150614,-0.150614,-0.022246,-0.022246,0.286638,0.286638,0.286638
StandardHours,float64,1100,0.00%,1,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
StockOptionLevel,float64,1100,0.00%,4,-0.148871,6.688052e-01,-1.011995,-1.011995,-1.011995,-0.728919,0.554588,0.554588,0.554588,0.554588
TotalWorkingYears,float64,1100,0.00%,28,-0.092541,6.989525e-01,-1.613335,-1.613335,-0.657823,-0.146998,0.153107,0.700300,1.734374,1.734374
TrainingTimesLastYear,float64,1100,0.00%,7,-0.018029,2.320854e-01,-0.552463,-0.552463,-0.314052,-0.128649,0.140684,0.204400,0.546149,0.546149
WorkLifeBalance,float64,1100,0.00%,4,-0.015876,2.147280e-01,-0.157361,-0.157361,-0.157361,-0.157361,0.099566,0.221653,0.649334,0.649334
YearsAtCompany,float64,1100,0.00%,24,-0.031681,5.563805e-01,-1.399761,-1.399761,-0.533771,-0.135022,0.336429,1.061615,1.061615,1.644762
YearsInCurrentRole,float64,1100,0.00%,15,-0.078784,6.026018e-01,-1.574114,-1.574114,-0.904683,0.049712,0.188834,0.739856,0.739856,0.951614
YearsSinceLastPromotion,float64,1100,0.00%,14,-0.010101,3.610881e-01,-1.245610,-1.245610,-0.657823,0.094164,0.201309,0.201309,0.546149,0.546149
YearsWithCurrManager,float64,1100,0.00%,17,-0.061409,5.191387e-01,-1.188452,-1.188452,-0.753134,-0.183365,-0.084477,0.890057,0.890057,0.951614

In [49]:
x_train

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,37,Travel_Rarely,Research & Development,1,4,Life Sciences,77,1,Male,2,...,3,80,1,7,2,4,7,5,0,7
1,54,Travel_Frequently,Research & Development,1,4,Life Sciences,1245,4,Female,3,...,1,80,1,33,2,1,5,4,1,4
2,34,Travel_Frequently,Research & Development,7,3,Life Sciences,147,1,Male,1,...,4,80,0,9,3,3,9,7,0,6
3,39,Travel_Rarely,Research & Development,1,1,Life Sciences,1026,4,Female,2,...,3,80,1,21,3,3,21,6,11,8
4,28,Travel_Frequently,Research & Development,1,3,Medical,1111,1,Male,2,...,1,80,2,1,2,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,35,Travel_Rarely,Research & Development,23,4,Medical,75,3,Female,3,...,3,80,1,4,3,3,2,2,2,2
1096,38,Travel_Rarely,Sales,2,4,Marketing,1835,2,Female,1,...,1,80,2,20,4,2,4,2,0,3
1097,37,Travel_Rarely,Sales,16,4,Marketing,868,4,Male,2,...,4,80,2,9,2,3,1,0,0,0
1098,22,Travel_Rarely,Research & Development,7,1,Life Sciences,1878,4,Male,3,...,1,80,0,1,2,3,1,0,0,0
1099,26,Travel_Frequently,Research & Development,2,3,Life Sciences,1053,1,Male,3,...,2,80,1,6,2,3,3,2,1,2

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score,roc_curve


lr_model =LogisticRegression(C=0.1,class_weight='balanced')  
lr_model.fit(x_train_woe,y_train)

y_pred = lr_model.predict_proba(x_train_woe)[:,1]
auc = roc_auc_score(y_train,y_pred)
fpr,tpr,_=roc_curve(y_train,y_pred)
ks = abs(fpr-tpr).max()
print('auc:',auc)
print('ks:',ks)

auc: 0.904689366058154
ks: 0.7054522410977602

In [58]:
y_pred = lr_model.predict_proba(x_test_woe)[:,1]
auc_t = roc_auc_score(y_test,y_pred)
fpr_t,tpr_t,_=roc_curve(y_test,y_pred)
ks_t = abs(fpr_t-tpr_t).max()
print('auc_t:',auc_t)
print('ks_t:',ks_t)

auc_t: 0.8153865701035513
ks_t: 0.503462295915126

In [59]:
import joblib
joblib.dump(lr_model,'Brain_drain.joblib')

['Brain_drain.joblib']